<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Base\**" />
		<EmbeddedResource Remove="Base\**" />
		<None Remove="Base\**" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Core\Persistence\Persistence.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="ESH.BuildingBlocks.Localization">
	    <HintPath>..\..\..\..\..\..\.nuget\packages\esh.buildingblocks.localization\1.0.1\lib\net9.0\ESH.BuildingBlocks.Localization.dll</HintPath>
	  </Reference>
	  <Reference Include="ESH.BuildingBlocks.Logging">
	    <HintPath>..\..\..\..\..\..\.nuget\packages\esh.buildingblocks.logging\1.0.1\lib\net9.0\ESH.BuildingBlocks.Logging.dll</HintPath>
	  </Reference>
	  <Reference Include="ESH.Helpers">
	    <HintPath>..\..\..\..\..\..\.nuget\packages\esh.helpers\1.0.1\lib\net9.0\ESH.Helpers.dll</HintPath>
	  </Reference>
	  <Reference Include="ESH.HttpServices">
	    <HintPath>..\..\..\..\..\..\.nuget\packages\esh.httpservice\1.0.1\lib\net9.0\ESH.HttpServices.dll</HintPath>
	  </Reference>
	</ItemGroup>

</Project>
