//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ButtonCaptions {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ButtonCaptions() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Resources.ButtonCaptions", typeof(ButtonCaptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        public static string BackToTicketsList {
            get {
                return ResourceManager.GetString("BackToTicketsList", resourceCulture);
            }
        }
        
        public static string CallToUser {
            get {
                return ResourceManager.GetString("CallToUser", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string ChangeActivation {
            get {
                return ResourceManager.GetString("ChangeActivation", resourceCulture);
            }
        }
        
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        public static string CloseAndTryAgain {
            get {
                return ResourceManager.GetString("CloseAndTryAgain", resourceCulture);
            }
        }
        
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string DeleteImage {
            get {
                return ResourceManager.GetString("DeleteImage", resourceCulture);
            }
        }
        
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        public static string FirstPage {
            get {
                return ResourceManager.GetString("FirstPage", resourceCulture);
            }
        }
        
        public static string GoToPage {
            get {
                return ResourceManager.GetString("GoToPage", resourceCulture);
            }
        }
        
        public static string LastPage {
            get {
                return ResourceManager.GetString("LastPage", resourceCulture);
            }
        }
        
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        public static string NeedToEdit {
            get {
                return ResourceManager.GetString("NeedToEdit", resourceCulture);
            }
        }
        
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        public static string ShowDetail {
            get {
                return ResourceManager.GetString("ShowDetail", resourceCulture);
            }
        }
        
        public static string ShowProfile {
            get {
                return ResourceManager.GetString("ShowProfile", resourceCulture);
            }
        }
        
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        public static string UpdateLargeImage {
            get {
                return ResourceManager.GetString("UpdateLargeImage", resourceCulture);
            }
        }
        
        public static string UpdateName {
            get {
                return ResourceManager.GetString("UpdateName", resourceCulture);
            }
        }
        
        public static string UpdateOrdering {
            get {
                return ResourceManager.GetString("UpdateOrdering", resourceCulture);
            }
        }
        
        public static string UpdateSmallImage {
            get {
                return ResourceManager.GetString("UpdateSmallImage", resourceCulture);
            }
        }
        
        public static string CreateTitle {
            get {
                return ResourceManager.GetString("CreateTitle", resourceCulture);
            }
        }
        
        public static string CreatePrice {
            get {
                return ResourceManager.GetString("CreatePrice", resourceCulture);
            }
        }
        
        public static string CreateLocation {
            get {
                return ResourceManager.GetString("CreateLocation", resourceCulture);
            }
        }
        
        public static string CreateRegion {
            get {
                return ResourceManager.GetString("CreateRegion", resourceCulture);
            }
        }
        
        public static string CreateDescription {
            get {
                return ResourceManager.GetString("CreateDescription", resourceCulture);
            }
        }
        
        public static string CreateImage {
            get {
                return ResourceManager.GetString("CreateImage", resourceCulture);
            }
        }
        
        public static string CreateOther {
            get {
                return ResourceManager.GetString("CreateOther", resourceCulture);
            }
        }
        
        public static string UpdateIcon {
            get {
                return ResourceManager.GetString("UpdateIcon", resourceCulture);
            }
        }
        
        public static string Commuting {
            get {
                return ResourceManager.GetString("Commuting", resourceCulture);
            }
        }
        
        public static string SuspensionHistory {
            get {
                return ResourceManager.GetString("SuspensionHistory", resourceCulture);
            }
        }
        
        public static string Announcements {
            get {
                return ResourceManager.GetString("Announcements", resourceCulture);
            }
        }
        
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        public static string Sessions {
            get {
                return ResourceManager.GetString("Sessions", resourceCulture);
            }
        }
        
        public static string AccountUnsuspension {
            get {
                return ResourceManager.GetString("AccountUnsuspension", resourceCulture);
            }
        }
        
        public static string UnsuspensionOfEveryone {
            get {
                return ResourceManager.GetString("UnsuspensionOfEveryone", resourceCulture);
            }
        }
        
        public static string SuspendIt {
            get {
                return ResourceManager.GetString("SuspendIt", resourceCulture);
            }
        }
        
        public static string CloseAllSessions {
            get {
                return ResourceManager.GetString("CloseAllSessions", resourceCulture);
            }
        }
        
        public static string AdvanceSearch {
            get {
                return ResourceManager.GetString("AdvanceSearch", resourceCulture);
            }
        }
        
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        public static string MyReports {
            get {
                return ResourceManager.GetString("MyReports", resourceCulture);
            }
        }
        
        public static string ReportedAnnouncements {
            get {
                return ResourceManager.GetString("ReportedAnnouncements", resourceCulture);
            }
        }
        
        public static string Favorite {
            get {
                return ResourceManager.GetString("Favorite", resourceCulture);
            }
        }
        
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        public static string NewMultiSelect {
            get {
                return ResourceManager.GetString("NewMultiSelect", resourceCulture);
            }
        }
        
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        public static string DeleteItem {
            get {
                return ResourceManager.GetString("DeleteItem", resourceCulture);
            }
        }
        
        public static string AddNewItem {
            get {
                return ResourceManager.GetString("AddNewItem", resourceCulture);
            }
        }
        
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        public static string DeleteAll {
            get {
                return ResourceManager.GetString("DeleteAll", resourceCulture);
            }
        }
        
        public static string SendOtp {
            get {
                return ResourceManager.GetString("SendOtp", resourceCulture);
            }
        }
        
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        public static string VerifyContinue {
            get {
                return ResourceManager.GetString("VerifyContinue", resourceCulture);
            }
        }
        
        public static string GoToLoginPage {
            get {
                return ResourceManager.GetString("GoToLoginPage", resourceCulture);
            }
        }
        
        public static string BackToHomePage {
            get {
                return ResourceManager.GetString("BackToHomePage", resourceCulture);
            }
        }
        
        public static string ViewSuspensionResponsible {
            get {
                return ResourceManager.GetString("ViewSuspensionResponsible", resourceCulture);
            }
        }
    }
}
