//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataDictionary_ar_OM {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataDictionary_ar_OM() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Resources.DataDictionary_ar_OM", typeof(DataDictionary_ar_OM).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Accounting {
            get {
                return ResourceManager.GetString("Accounting", resourceCulture);
            }
        }
        
        public static string AccountUnsuspension {
            get {
                return ResourceManager.GetString("AccountUnsuspension", resourceCulture);
            }
        }
        
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        public static string ActionCode {
            get {
                return ResourceManager.GetString("ActionCode", resourceCulture);
            }
        }
        
        public static string ActionType {
            get {
                return ResourceManager.GetString("ActionType", resourceCulture);
            }
        }
        
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        public static string ActiveCategories {
            get {
                return ResourceManager.GetString("ActiveCategories", resourceCulture);
            }
        }
        
        public static string AddAnswer {
            get {
                return ResourceManager.GetString("AddAnswer", resourceCulture);
            }
        }
        
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        public static string AddressSummary {
            get {
                return ResourceManager.GetString("AddressSummary", resourceCulture);
            }
        }
        
        public static string AdvanceSearch {
            get {
                return ResourceManager.GetString("AdvanceSearch", resourceCulture);
            }
        }
        
        public static string Alternative {
            get {
                return ResourceManager.GetString("Alternative", resourceCulture);
            }
        }
        
        public static string Announcement {
            get {
                return ResourceManager.GetString("Announcement", resourceCulture);
            }
        }
        
        public static string AnnouncementsStatus {
            get {
                return ResourceManager.GetString("AnnouncementsStatus", resourceCulture);
            }
        }
        
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        public static string Answered {
            get {
                return ResourceManager.GetString("Answered", resourceCulture);
            }
        }
        
        public static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        public static string ArOmCode {
            get {
                return ResourceManager.GetString("ArOmCode", resourceCulture);
            }
        }
        
        public static string Attachment {
            get {
                return ResourceManager.GetString("Attachment", resourceCulture);
            }
        }
        
        public static string AttachmentSubject {
            get {
                return ResourceManager.GetString("AttachmentSubject", resourceCulture);
            }
        }
        
        public static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        public static string Banner {
            get {
                return ResourceManager.GetString("Banner", resourceCulture);
            }
        }
        
        public static string Browser {
            get {
                return ResourceManager.GetString("Browser", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string Captcha {
            get {
                return ResourceManager.GetString("Captcha", resourceCulture);
            }
        }
        
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        public static string CategoryType {
            get {
                return ResourceManager.GetString("CategoryType", resourceCulture);
            }
        }
        
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        public static string ChangeStatusClosed {
            get {
                return ResourceManager.GetString("ChangeStatusClosed", resourceCulture);
            }
        }
        
        public static string ChangeStatusToUnderReview {
            get {
                return ResourceManager.GetString("ChangeStatusToUnderReview", resourceCulture);
            }
        }
        
        public static string Charts {
            get {
                return ResourceManager.GetString("Charts", resourceCulture);
            }
        }
        
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        public static string CloseAndTryAgain {
            get {
                return ResourceManager.GetString("CloseAndTryAgain", resourceCulture);
            }
        }
        
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        public static string Commuting {
            get {
                return ResourceManager.GetString("Commuting", resourceCulture);
            }
        }
        
        public static string CommutingType {
            get {
                return ResourceManager.GetString("CommutingType", resourceCulture);
            }
        }
        
        public static string Confirmed {
            get {
                return ResourceManager.GetString("Confirmed", resourceCulture);
            }
        }
        
        public static string Contains {
            get {
                return ResourceManager.GetString("Contains", resourceCulture);
            }
        }
        
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        public static string ContentType {
            get {
                return ResourceManager.GetString("ContentType", resourceCulture);
            }
        }
        
        public static string ControllerName {
            get {
                return ResourceManager.GetString("ControllerName", resourceCulture);
            }
        }
        
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        public static string CountAllUsers {
            get {
                return ResourceManager.GetString("CountAllUsers", resourceCulture);
            }
        }
        
        public static string CountAllUsersActive {
            get {
                return ResourceManager.GetString("CountAllUsersActive", resourceCulture);
            }
        }
        
        public static string CountAllUsersDeActive {
            get {
                return ResourceManager.GetString("CountAllUsersDeActive", resourceCulture);
            }
        }
        
        public static string CountInEveryPage {
            get {
                return ResourceManager.GetString("CountInEveryPage", resourceCulture);
            }
        }
        
        public static string Cover {
            get {
                return ResourceManager.GetString("Cover", resourceCulture);
            }
        }
        
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        public static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        public static string CustomerAffairs {
            get {
                return ResourceManager.GetString("CustomerAffairs", resourceCulture);
            }
        }
        
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        public static string DashboardLink {
            get {
                return ResourceManager.GetString("DashboardLink", resourceCulture);
            }
        }
        
        public static string DashboardRole {
            get {
                return ResourceManager.GetString("DashboardRole", resourceCulture);
            }
        }
        
        public static string DataType {
            get {
                return ResourceManager.GetString("DataType", resourceCulture);
            }
        }
        
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        public static string DeActive {
            get {
                return ResourceManager.GetString("DeActive", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string DeleteImage {
            get {
                return ResourceManager.GetString("DeleteImage", resourceCulture);
            }
        }
        
        public static string DeleteReason {
            get {
                return ResourceManager.GetString("DeleteReason", resourceCulture);
            }
        }
        
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        public static string DeviceModel {
            get {
                return ResourceManager.GetString("DeviceModel", resourceCulture);
            }
        }
        
        public static string DictionaryChecker {
            get {
                return ResourceManager.GetString("DictionaryChecker", resourceCulture);
            }
        }
        
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        public static string EndDateTime {
            get {
                return ResourceManager.GetString("EndDateTime", resourceCulture);
            }
        }
        
        public static string EnUsCode {
            get {
                return ResourceManager.GetString("EnUsCode", resourceCulture);
            }
        }
        
        public static string ErrorReport {
            get {
                return ResourceManager.GetString("ErrorReport", resourceCulture);
            }
        }
        
        public static string Faq {
            get {
                return ResourceManager.GetString("Faq", resourceCulture);
            }
        }
        
        public static string Favorite {
            get {
                return ResourceManager.GetString("Favorite", resourceCulture);
            }
        }
        
        public static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        public static string FieldName {
            get {
                return ResourceManager.GetString("FieldName", resourceCulture);
            }
        }
        
        public static string Fields {
            get {
                return ResourceManager.GetString("Fields", resourceCulture);
            }
        }
        
        public static string FieldType {
            get {
                return ResourceManager.GetString("FieldType", resourceCulture);
            }
        }
        
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        public static string FileLarge {
            get {
                return ResourceManager.GetString("FileLarge", resourceCulture);
            }
        }
        
        public static string FileMobile {
            get {
                return ResourceManager.GetString("FileMobile", resourceCulture);
            }
        }
        
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        public static string FileSmall {
            get {
                return ResourceManager.GetString("FileSmall", resourceCulture);
            }
        }
        
        public static string FileSubSystemLocal {
            get {
                return ResourceManager.GetString("FileSubSystemLocal", resourceCulture);
            }
        }
        
        public static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        public static string FileWeb {
            get {
                return ResourceManager.GetString("FileWeb", resourceCulture);
            }
        }
        
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        public static string FilterAndSort {
            get {
                return ResourceManager.GetString("FilterAndSort", resourceCulture);
            }
        }
        
        public static string FinancialSupport {
            get {
                return ResourceManager.GetString("FinancialSupport", resourceCulture);
            }
        }
        
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        public static string ForegroundColor {
            get {
                return ResourceManager.GetString("ForegroundColor", resourceCulture);
            }
        }
        
        public static string FullPhoneNumber {
            get {
                return ResourceManager.GetString("FullPhoneNumber", resourceCulture);
            }
        }
        
        public static string GetAgain {
            get {
                return ResourceManager.GetString("GetAgain", resourceCulture);
            }
        }
        
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        public static string GroupByName {
            get {
                return ResourceManager.GetString("GroupByName", resourceCulture);
            }
        }
        
        public static string Guid {
            get {
                return ResourceManager.GetString("Guid", resourceCulture);
            }
        }
        
        public static string GuidName {
            get {
                return ResourceManager.GetString("GuidName", resourceCulture);
            }
        }
        
        public static string HasDescription {
            get {
                return ResourceManager.GetString("HasDescription", resourceCulture);
            }
        }
        
        public static string HasNeedToCheckFields {
            get {
                return ResourceManager.GetString("HasNeedToCheckFields", resourceCulture);
            }
        }
        
        public static string HasNeedToDefaultFields {
            get {
                return ResourceManager.GetString("HasNeedToDefaultFields", resourceCulture);
            }
        }
        
        public static string HasWarningDictionaryChecker {
            get {
                return ResourceManager.GetString("HasWarningDictionaryChecker", resourceCulture);
            }
        }
        
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        public static string Hint {
            get {
                return ResourceManager.GetString("Hint", resourceCulture);
            }
        }
        
        public static string Href {
            get {
                return ResourceManager.GetString("Href", resourceCulture);
            }
        }
        
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        public static string ImageTitle {
            get {
                return ResourceManager.GetString("ImageTitle", resourceCulture);
            }
        }
        
        public static string InactiveCategories {
            get {
                return ResourceManager.GetString("InactiveCategories", resourceCulture);
            }
        }
        
        public static string IpAddress {
            get {
                return ResourceManager.GetString("IpAddress", resourceCulture);
            }
        }
        
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        public static string IsActiveInMobile {
            get {
                return ResourceManager.GetString("IsActiveInMobile", resourceCulture);
            }
        }
        
        public static string IsActiveInWeb {
            get {
                return ResourceManager.GetString("IsActiveInWeb", resourceCulture);
            }
        }
        
        public static string IsCheck {
            get {
                return ResourceManager.GetString("IsCheck", resourceCulture);
            }
        }
        
        public static string IsClicked {
            get {
                return ResourceManager.GetString("IsClicked", resourceCulture);
            }
        }
        
        public static string IsConnectToSystemBugs {
            get {
                return ResourceManager.GetString("IsConnectToSystemBugs", resourceCulture);
            }
        }
        
        public static string IsDefault {
            get {
                return ResourceManager.GetString("IsDefault", resourceCulture);
            }
        }
        
        public static string IsForceUpdate {
            get {
                return ResourceManager.GetString("IsForceUpdate", resourceCulture);
            }
        }
        
        public static string IsHidden {
            get {
                return ResourceManager.GetString("IsHidden", resourceCulture);
            }
        }
        
        public static string IsHiddenCahrs {
            get {
                return ResourceManager.GetString("IsHiddenCahrs", resourceCulture);
            }
        }
        
        public static string IsLocked {
            get {
                return ResourceManager.GetString("IsLocked", resourceCulture);
            }
        }
        
        public static string IsPrimary {
            get {
                return ResourceManager.GetString("IsPrimary", resourceCulture);
            }
        }
        
        public static string IsPublic {
            get {
                return ResourceManager.GetString("IsPublic", resourceCulture);
            }
        }
        
        public static string IsRequired {
            get {
                return ResourceManager.GetString("IsRequired", resourceCulture);
            }
        }
        
        public static string IsRtl {
            get {
                return ResourceManager.GetString("IsRtl", resourceCulture);
            }
        }
        
        public static string IsSeen {
            get {
                return ResourceManager.GetString("IsSeen", resourceCulture);
            }
        }
        
        public static string IsSend {
            get {
                return ResourceManager.GetString("IsSend", resourceCulture);
            }
        }
        
        public static string IsShowProfileInAnnouncement {
            get {
                return ResourceManager.GetString("IsShowProfileInAnnouncement", resourceCulture);
            }
        }
        
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        public static string JsonConfig {
            get {
                return ResourceManager.GetString("JsonConfig", resourceCulture);
            }
        }
        
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        public static string LanguageCode {
            get {
                return ResourceManager.GetString("LanguageCode", resourceCulture);
            }
        }
        
        public static string LastException {
            get {
                return ResourceManager.GetString("LastException", resourceCulture);
            }
        }
        
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        public static string LastPage {
            get {
                return ResourceManager.GetString("LastPage", resourceCulture);
            }
        }
        
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        public static string LinkImage {
            get {
                return ResourceManager.GetString("LinkImage", resourceCulture);
            }
        }
        
        public static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        public static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        public static string MaxAttachmentSizeMB {
            get {
                return ResourceManager.GetString("MaxAttachmentSizeMB", resourceCulture);
            }
        }
        
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        public static string Method {
            get {
                return ResourceManager.GetString("Method", resourceCulture);
            }
        }
        
        public static string MonthlyAnnouncements {
            get {
                return ResourceManager.GetString("MonthlyAnnouncements", resourceCulture);
            }
        }
        
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        public static string MultipleValuesAreRequired {
            get {
                return ResourceManager.GetString("MultipleValuesAreRequired", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string NameLocalize {
            get {
                return ResourceManager.GetString("NameLocalize", resourceCulture);
            }
        }
        
        public static string NeedToCheck {
            get {
                return ResourceManager.GetString("NeedToCheck", resourceCulture);
            }
        }
        
        public static string NeedToEditReason {
            get {
                return ResourceManager.GetString("NeedToEditReason", resourceCulture);
            }
        }
        
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        public static string NoSaved {
            get {
                return ResourceManager.GetString("NoSaved", resourceCulture);
            }
        }
        
        public static string NotConfirmed {
            get {
                return ResourceManager.GetString("NotConfirmed", resourceCulture);
            }
        }
        
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        public static string NotSendFromServer {
            get {
                return ResourceManager.GetString("NotSendFromServer", resourceCulture);
            }
        }
        
        public static string OffensiveSuspiciousWords {
            get {
                return ResourceManager.GetString("OffensiveSuspiciousWords", resourceCulture);
            }
        }
        
        public static string OnDelete {
            get {
                return ResourceManager.GetString("OnDelete", resourceCulture);
            }
        }
        
        public static string Opration {
            get {
                return ResourceManager.GetString("Opration", resourceCulture);
            }
        }
        
        public static string Optinal {
            get {
                return ResourceManager.GetString("Optinal", resourceCulture);
            }
        }
        
        public static string Ordering {
            get {
                return ResourceManager.GetString("Ordering", resourceCulture);
            }
        }
        
        public static string OtpCode {
            get {
                return ResourceManager.GetString("OtpCode", resourceCulture);
            }
        }
        
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        public static string PageAccess {
            get {
                return ResourceManager.GetString("PageAccess", resourceCulture);
            }
        }
        
        public static string PageCode {
            get {
                return ResourceManager.GetString("PageCode", resourceCulture);
            }
        }
        
        public static string PageDynamic {
            get {
                return ResourceManager.GetString("PageDynamic", resourceCulture);
            }
        }
        
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        public static string PageSetting {
            get {
                return ResourceManager.GetString("PageSetting", resourceCulture);
            }
        }
        
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        public static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        public static string PendingApproval {
            get {
                return ResourceManager.GetString("PendingApproval", resourceCulture);
            }
        }
        
        public static string Percent {
            get {
                return ResourceManager.GetString("Percent", resourceCulture);
            }
        }
        
        public static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        public static string PhoneNumberType {
            get {
                return ResourceManager.GetString("PhoneNumberType", resourceCulture);
            }
        }
        
        public static string PhoneOperator {
            get {
                return ResourceManager.GetString("PhoneOperator", resourceCulture);
            }
        }
        
        public static string PinInMobile {
            get {
                return ResourceManager.GetString("PinInMobile", resourceCulture);
            }
        }
        
        public static string PlateCode {
            get {
                return ResourceManager.GetString("PlateCode", resourceCulture);
            }
        }
        
        public static string PlateNumber {
            get {
                return ResourceManager.GetString("PlateNumber", resourceCulture);
            }
        }
        
        public static string PlateNumberType {
            get {
                return ResourceManager.GetString("PlateNumberType", resourceCulture);
            }
        }
        
        public static string PlateStatus {
            get {
                return ResourceManager.GetString("PlateStatus", resourceCulture);
            }
        }
        
        public static string PrePhoneNumber {
            get {
                return ResourceManager.GetString("PrePhoneNumber", resourceCulture);
            }
        }
        
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        public static string PropertyName {
            get {
                return ResourceManager.GetString("PropertyName", resourceCulture);
            }
        }
        
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        public static string QualityControl {
            get {
                return ResourceManager.GetString("QualityControl", resourceCulture);
            }
        }
        
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        public static string QuestionSystem {
            get {
                return ResourceManager.GetString("QuestionSystem", resourceCulture);
            }
        }
        
        public static string ReadTime {
            get {
                return ResourceManager.GetString("ReadTime", resourceCulture);
            }
        }
        
        public static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        public static string Referesh {
            get {
                return ResourceManager.GetString("Referesh", resourceCulture);
            }
        }
        
        public static string Regex {
            get {
                return ResourceManager.GetString("Regex", resourceCulture);
            }
        }
        
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        public static string Relation {
            get {
                return ResourceManager.GetString("Relation", resourceCulture);
            }
        }
        
        public static string ReleaseNote {
            get {
                return ResourceManager.GetString("ReleaseNote", resourceCulture);
            }
        }
        
        public static string ReplaceCharsWhenIsHidden {
            get {
                return ResourceManager.GetString("ReplaceCharsWhenIsHidden", resourceCulture);
            }
        }
        
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        public static string ReportedByUsers {
            get {
                return ResourceManager.GetString("ReportedByUsers", resourceCulture);
            }
        }
        
        public static string ReportReason {
            get {
                return ResourceManager.GetString("ReportReason", resourceCulture);
            }
        }
        
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        public static string RetryCount {
            get {
                return ResourceManager.GetString("RetryCount", resourceCulture);
            }
        }
        
        public static string ReviewPending {
            get {
                return ResourceManager.GetString("ReviewPending", resourceCulture);
            }
        }
        
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        public static string RolesManager {
            get {
                return ResourceManager.GetString("RolesManager", resourceCulture);
            }
        }
        
        public static string Route {
            get {
                return ResourceManager.GetString("Route", resourceCulture);
            }
        }
        
        public static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        public static string SeenCount {
            get {
                return ResourceManager.GetString("SeenCount", resourceCulture);
            }
        }
        
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        public static string SendDate {
            get {
                return ResourceManager.GetString("SendDate", resourceCulture);
            }
        }
        
        public static string SendNow {
            get {
                return ResourceManager.GetString("SendNow", resourceCulture);
            }
        }
        
        public static string SendNowFeature {
            get {
                return ResourceManager.GetString("SendNowFeature", resourceCulture);
            }
        }
        
        public static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        public static string ServerId {
            get {
                return ResourceManager.GetString("ServerId", resourceCulture);
            }
        }
        
        public static string ServerOrSubSystem {
            get {
                return ResourceManager.GetString("ServerOrSubSystem", resourceCulture);
            }
        }
        
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        public static string ShowNotification {
            get {
                return ResourceManager.GetString("ShowNotification", resourceCulture);
            }
        }
        
        public static string Social {
            get {
                return ResourceManager.GetString("Social", resourceCulture);
            }
        }
        
        public static string StartDateTime {
            get {
                return ResourceManager.GetString("StartDateTime", resourceCulture);
            }
        }
        
        public static string StartWith {
            get {
                return ResourceManager.GetString("StartWith", resourceCulture);
            }
        }
        
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        public static string SubmitForm {
            get {
                return ResourceManager.GetString("SubmitForm", resourceCulture);
            }
        }
        
        public static string SubSystem {
            get {
                return ResourceManager.GetString("SubSystem", resourceCulture);
            }
        }
        
        public static string SubSystemLocal {
            get {
                return ResourceManager.GetString("SubSystemLocal", resourceCulture);
            }
        }
        
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        public static string SuspensionHistory {
            get {
                return ResourceManager.GetString("SuspensionHistory", resourceCulture);
            }
        }
        
        public static string SuspensionHistoryId {
            get {
                return ResourceManager.GetString("SuspensionHistoryId", resourceCulture);
            }
        }
        
        public static string SystemMessage {
            get {
                return ResourceManager.GetString("SystemMessage", resourceCulture);
            }
        }
        
        public static string TagPageSetting {
            get {
                return ResourceManager.GetString("TagPageSetting", resourceCulture);
            }
        }
        
        public static string TagSettings {
            get {
                return ResourceManager.GetString("TagSettings", resourceCulture);
            }
        }
        
        public static string TargetIsBlank {
            get {
                return ResourceManager.GetString("TargetIsBlank", resourceCulture);
            }
        }
        
        public static string TechnicalSupport {
            get {
                return ResourceManager.GetString("TechnicalSupport", resourceCulture);
            }
        }
        
        public static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        public static string TextDynamic {
            get {
                return ResourceManager.GetString("TextDynamic", resourceCulture);
            }
        }
        
        public static string ThisMonthAnnouncements {
            get {
                return ResourceManager.GetString("ThisMonthAnnouncements", resourceCulture);
            }
        }
        
        public static string ThisMonthUsers {
            get {
                return ResourceManager.GetString("ThisMonthUsers", resourceCulture);
            }
        }
        
        public static string ThisWeekAnnouncements {
            get {
                return ResourceManager.GetString("ThisWeekAnnouncements", resourceCulture);
            }
        }
        
        public static string ThisWeekUsers {
            get {
                return ResourceManager.GetString("ThisWeekUsers", resourceCulture);
            }
        }
        
        public static string Ticket {
            get {
                return ResourceManager.GetString("Ticket", resourceCulture);
            }
        }
        
        public static string TicketMessage {
            get {
                return ResourceManager.GetString("TicketMessage", resourceCulture);
            }
        }
        
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        public static string TodayAnnouncements {
            get {
                return ResourceManager.GetString("TodayAnnouncements", resourceCulture);
            }
        }
        
        public static string TodayUsers {
            get {
                return ResourceManager.GetString("TodayUsers", resourceCulture);
            }
        }
        
        public static string Token {
            get {
                return ResourceManager.GetString("Token", resourceCulture);
            }
        }
        
        public static string TopCategories {
            get {
                return ResourceManager.GetString("TopCategories", resourceCulture);
            }
        }
        
        public static string TotalAnnouncements {
            get {
                return ResourceManager.GetString("TotalAnnouncements", resourceCulture);
            }
        }
        
        public static string TotalCategories {
            get {
                return ResourceManager.GetString("TotalCategories", resourceCulture);
            }
        }
        
        public static string TotalCount {
            get {
                return ResourceManager.GetString("TotalCount", resourceCulture);
            }
        }
        
        public static string TotalPages {
            get {
                return ResourceManager.GetString("TotalPages", resourceCulture);
            }
        }
        
        public static string TotalUsers {
            get {
                return ResourceManager.GetString("TotalUsers", resourceCulture);
            }
        }
        
        public static string Typing {
            get {
                return ResourceManager.GetString("Typing", resourceCulture);
            }
        }
        
        public static string UnderReview {
            get {
                return ResourceManager.GetString("UnderReview", resourceCulture);
            }
        }
        
        public static string UpdateDate {
            get {
                return ResourceManager.GetString("UpdateDate", resourceCulture);
            }
        }
        
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        public static string UseDefaultNames {
            get {
                return ResourceManager.GetString("UseDefaultNames", resourceCulture);
            }
        }
        
        public static string UseInMobileApp {
            get {
                return ResourceManager.GetString("UseInMobileApp", resourceCulture);
            }
        }
        
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        public static string UserCode {
            get {
                return ResourceManager.GetString("UserCode", resourceCulture);
            }
        }
        
        public static string UserRelation {
            get {
                return ResourceManager.GetString("UserRelation", resourceCulture);
            }
        }
        
        public static string UsersGrowth {
            get {
                return ResourceManager.GetString("UsersGrowth", resourceCulture);
            }
        }
        
        public static string UserSuspension {
            get {
                return ResourceManager.GetString("UserSuspension", resourceCulture);
            }
        }
        
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        public static string VideoBox {
            get {
                return ResourceManager.GetString("VideoBox", resourceCulture);
            }
        }
        
        public static string ViewCount {
            get {
                return ResourceManager.GetString("ViewCount", resourceCulture);
            }
        }
        
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        public static string PinInHome {
            get {
                return ResourceManager.GetString("PinInHome", resourceCulture);
            }
        }
        
        public static string Day_1 {
            get {
                return ResourceManager.GetString("Day_1", resourceCulture);
            }
        }
        
        public static string Week_1 {
            get {
                return ResourceManager.GetString("Week_1", resourceCulture);
            }
        }
        
        public static string Month_1 {
            get {
                return ResourceManager.GetString("Month_1", resourceCulture);
            }
        }
        
        public static string Months_6 {
            get {
                return ResourceManager.GetString("Months_6", resourceCulture);
            }
        }
        
        public static string UnbanDate {
            get {
                return ResourceManager.GetString("UnbanDate", resourceCulture);
            }
        }
        
        public static string PhoneSuspendedUser {
            get {
                return ResourceManager.GetString("PhoneSuspendedUser", resourceCulture);
            }
        }
        
        public static string ActionBy {
            get {
                return ResourceManager.GetString("ActionBy", resourceCulture);
            }
        }
        
        public static string UnsuspensionDate {
            get {
                return ResourceManager.GetString("UnsuspensionDate", resourceCulture);
            }
        }
        
        public static string ImageGallery {
            get {
                return ResourceManager.GetString("ImageGallery", resourceCulture);
            }
        }
        
        public static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
    }
}
