//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotificationTemplates_ar_OM {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationTemplates_ar_OM() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Resources.NotificationTemplates_ar_OM", typeof(NotificationTemplates_ar_OM).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AnnouncementStatus10 {
            get {
                return ResourceManager.GetString("AnnouncementStatus10", resourceCulture);
            }
        }
        
        public static string AnnouncementStatus10Title {
            get {
                return ResourceManager.GetString("AnnouncementStatus10Title", resourceCulture);
            }
        }
        
        public static string AnnouncementStatus20 {
            get {
                return ResourceManager.GetString("AnnouncementStatus20", resourceCulture);
            }
        }
        
        public static string AnnouncementStatus20Title {
            get {
                return ResourceManager.GetString("AnnouncementStatus20Title", resourceCulture);
            }
        }
        
        public static string AnnouncementStatus30 {
            get {
                return ResourceManager.GetString("AnnouncementStatus30", resourceCulture);
            }
        }
        
        public static string AnnouncementStatus30Title {
            get {
                return ResourceManager.GetString("AnnouncementStatus30Title", resourceCulture);
            }
        }
        
        public static string AnnouncementStatus40 {
            get {
                return ResourceManager.GetString("AnnouncementStatus40", resourceCulture);
            }
        }
        
        public static string AnnouncementStatus40Title {
            get {
                return ResourceManager.GetString("AnnouncementStatus40Title", resourceCulture);
            }
        }
        
        public static string AnnouncementStatus50 {
            get {
                return ResourceManager.GetString("AnnouncementStatus50", resourceCulture);
            }
        }
        
        public static string AnnouncementStatus50Title {
            get {
                return ResourceManager.GetString("AnnouncementStatus50Title", resourceCulture);
            }
        }
        
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        public static string Otp {
            get {
                return ResourceManager.GetString("Otp", resourceCulture);
            }
        }
        
        public static string OtpTitle {
            get {
                return ResourceManager.GetString("OtpTitle", resourceCulture);
            }
        }
        
        public static string TicketReviewClosed {
            get {
                return ResourceManager.GetString("TicketReviewClosed", resourceCulture);
            }
        }
        
        public static string TicketReviewClosedTitle {
            get {
                return ResourceManager.GetString("TicketReviewClosedTitle", resourceCulture);
            }
        }
        
        public static string TicketReviewPending {
            get {
                return ResourceManager.GetString("TicketReviewPending", resourceCulture);
            }
        }
        
        public static string TicketReviewPendingTitle {
            get {
                return ResourceManager.GetString("TicketReviewPendingTitle", resourceCulture);
            }
        }
        
        public static string TicketUnderAnswered {
            get {
                return ResourceManager.GetString("TicketUnderAnswered", resourceCulture);
            }
        }
        
        public static string TicketUnderAnsweredTitle {
            get {
                return ResourceManager.GetString("TicketUnderAnsweredTitle", resourceCulture);
            }
        }
        
        public static string TicketUnderReview {
            get {
                return ResourceManager.GetString("TicketUnderReview", resourceCulture);
            }
        }
        
        public static string TicketUnderReviewTitle {
            get {
                return ResourceManager.GetString("TicketUnderReviewTitle", resourceCulture);
            }
        }
        
        public static string VerifyAccountSuccess {
            get {
                return ResourceManager.GetString("VerifyAccountSuccess", resourceCulture);
            }
        }
        
        public static string VerifyAccountSuccessTitle {
            get {
                return ResourceManager.GetString("VerifyAccountSuccessTitle", resourceCulture);
            }
        }
    }
}
