//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PageTitles {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PageTitles() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Resources.PageTitles", typeof(PageTitles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AccessLevels {
            get {
                return ResourceManager.GetString("AccessLevels", resourceCulture);
            }
        }
        
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        public static string Banner {
            get {
                return ResourceManager.GetString("Banner", resourceCulture);
            }
        }
        
        public static string Faq {
            get {
                return ResourceManager.GetString("Faq", resourceCulture);
            }
        }
        
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        public static string PageDynamic {
            get {
                return ResourceManager.GetString("PageDynamic", resourceCulture);
            }
        }
        
        public static string PageSettings {
            get {
                return ResourceManager.GetString("PageSettings", resourceCulture);
            }
        }
        
        public static string PanelAdminTitle {
            get {
                return ResourceManager.GetString("PanelAdminTitle", resourceCulture);
            }
        }
        
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        public static string RoleManager {
            get {
                return ResourceManager.GetString("RoleManager", resourceCulture);
            }
        }
        
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        public static string Social {
            get {
                return ResourceManager.GetString("Social", resourceCulture);
            }
        }
        
        public static string SuspensionsHistory {
            get {
                return ResourceManager.GetString("SuspensionsHistory", resourceCulture);
            }
        }
        
        public static string TextDynamic {
            get {
                return ResourceManager.GetString("TextDynamic", resourceCulture);
            }
        }
        
        public static string TicketsManager {
            get {
                return ResourceManager.GetString("TicketsManager", resourceCulture);
            }
        }
        
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        public static string VideoBox {
            get {
                return ResourceManager.GetString("VideoBox", resourceCulture);
            }
        }
        
        public static string AnnouncementCategory {
            get {
                return ResourceManager.GetString("AnnouncementCategory", resourceCulture);
            }
        }
        
        public static string Announcement {
            get {
                return ResourceManager.GetString("Announcement", resourceCulture);
            }
        }
        
        public static string Fields {
            get {
                return ResourceManager.GetString("Fields", resourceCulture);
            }
        }
        
        public static string DeleteReason {
            get {
                return ResourceManager.GetString("DeleteReason", resourceCulture);
            }
        }
        
        public static string ReportReason {
            get {
                return ResourceManager.GetString("ReportReason", resourceCulture);
            }
        }
        
        public static string NeedToEditReason {
            get {
                return ResourceManager.GetString("NeedToEditReason", resourceCulture);
            }
        }
        
        public static string Sessions {
            get {
                return ResourceManager.GetString("Sessions", resourceCulture);
            }
        }
        
        public static string UserActiveSessions {
            get {
                return ResourceManager.GetString("UserActiveSessions", resourceCulture);
            }
        }
        
        public static string ForbiddenWordsManagement {
            get {
                return ResourceManager.GetString("ForbiddenWordsManagement", resourceCulture);
            }
        }
        
        public static string ada {
            get {
                return ResourceManager.GetString("ada", resourceCulture);
            }
        }
        
        public static string LinkImage {
            get {
                return ResourceManager.GetString("LinkImage", resourceCulture);
            }
        }
        
        public static string RegisterField {
            get {
                return ResourceManager.GetString("RegisterField", resourceCulture);
            }
        }
        
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        public static string ActionPage {
            get {
                return ResourceManager.GetString("ActionPage", resourceCulture);
            }
        }
    }
}
