<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    
  <ItemGroup>
    <Compile Update="ButtonCaptions.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ButtonCaptions.resx</DependentUpon>
    </Compile>
    <Compile Update="DataDictionary.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DataDictionary.resx</DependentUpon>
    </Compile>
    <Compile Update="Messages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Messages.resx</DependentUpon>
    </Compile>
    <Compile Update="PageTitles.ar-OM.Designer.cs">
      <DependentUpon>PageTitles.ar-OM.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="PageTitles.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>PageTitles.resx</DependentUpon>
    </Compile>
    <Compile Update="PlateNumberTypes.ar-OM.Designer.cs">
      <DependentUpon>PlateNumberTypes.ar-OM.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Roles.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Roles.resx</DependentUpon>
    </Compile>
    <Compile Update="Dashboards.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Dashboards.resx</DependentUpon>
    </Compile>
    <Compile Update="ResponseErrors.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ResponseErrors.resx</DependentUpon>
    </Compile>
    <Compile Update="Banks.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Banks.resx</DependentUpon>
    </Compile>
    <Compile Update="NotificationCategories.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>NotificationCategories.resx</DependentUpon>
    </Compile>
    <Compile Update="NotificationTemplates.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>NotificationTemplates.resx</DependentUpon>
    </Compile>
    <Compile Update="OrderStatusList.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>OrderStatusList.resx</DependentUpon>
    </Compile>
    <Compile Update="SortTitle.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SortTitle.resx</DependentUpon>
    </Compile>
    <Compile Update="PlateNumberTypes.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>PlateNumberTypes.resx</DependentUpon>
    </Compile>
    <Compile Update="ButtonCaptions.ar-OM.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ButtonCaptions.ar-OM.resx</DependentUpon>
    </Compile>
    <Compile Update="PlateNumberTypes.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>PlateNumberTypes.resx</DependentUpon>
    </Compile>
    <Compile Update="DataDictionary.ar-OM.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DataDictionary.ar-OM.resx</DependentUpon>
    </Compile>
    <Compile Update="Messages.ar-OM.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Messages.ar-OM.resx</DependentUpon>
    </Compile>
    <Compile Update="ResponseErrors.ar-OM.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ResponseErrors.ar-OM.resx</DependentUpon>
    </Compile>
    <Compile Update="NotificationTemplates.ar-OM.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>NotificationTemplates.ar-OM.resx</DependentUpon>
    </Compile>
    <Compile Update="SortTitle.ar-OM.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SortTitle.ar-OM.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="ButtonCaptions.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ButtonCaptions.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="DataDictionary.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>DataDictionary.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Messages.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Messages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="PageTitles.ar-OM.resx">
      <LastGenOutput>PageTitles.ar-OM.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="PageTitles.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>PageTitles.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="PlateNumberTypes.ar-OM.resx">
      <LastGenOutput>PlateNumberTypes.ar-OM.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Roles.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Roles.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Dashboards.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Dashboards.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="ResponseErrors.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ResponseErrors.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Banks.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Banks.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="NotificationCategories.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>NotificationCategories.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="NotificationTemplates.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>NotificationTemplates.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="OrderStatusList.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>OrderStatusList.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="SortTitle.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>SortTitle.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="PlateNumberTypes.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>PlateNumberTypes.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="ButtonCaptions.ar-OM.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ButtonCaptions.ar-OM.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="PlateNumberTypes.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>PlateNumberTypes.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="DataDictionary.ar-OM.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>DataDictionary.ar-OM.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Messages.ar-OM.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Messages.ar-OM.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="ResponseErrors.ar-OM.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ResponseErrors.ar-OM.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="NotificationTemplates.ar-OM.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>NotificationTemplates.ar-OM.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="SortTitle.ar-OM.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>SortTitle.ar-OM.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>